create table "public"."plan" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "name" text,
    "email" character varying,
    "stripe_customer_id" text,
    "subscription_status" text,
    "price" text,
    "user_id" uuid not null
);


CREATE UNIQUE INDEX plan_email_key ON public.plan USING btree (email);

CREATE UNIQUE INDEX plan_pkey ON public.plan USING btree (id);

alter table "public"."plan" add constraint "plan_pkey" PRIMARY KEY using index "plan_pkey";

alter table "public"."plan" add constraint "plan_email_key" UNIQUE using index "plan_email_key";

alter table "public"."plan" add constraint "plan_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."plan" validate constraint "plan_user_id_fkey";

grant delete on table "public"."plan" to "anon";

grant insert on table "public"."plan" to "anon";

grant references on table "public"."plan" to "anon";

grant select on table "public"."plan" to "anon";

grant trigger on table "public"."plan" to "anon";

grant truncate on table "public"."plan" to "anon";

grant update on table "public"."plan" to "anon";

grant delete on table "public"."plan" to "authenticated";

grant insert on table "public"."plan" to "authenticated";

grant references on table "public"."plan" to "authenticated";

grant select on table "public"."plan" to "authenticated";

grant trigger on table "public"."plan" to "authenticated";

grant truncate on table "public"."plan" to "authenticated";

grant update on table "public"."plan" to "authenticated";

grant delete on table "public"."plan" to "service_role";

grant insert on table "public"."plan" to "service_role";

grant references on table "public"."plan" to "service_role";

grant select on table "public"."plan" to "service_role";

grant trigger on table "public"."plan" to "service_role";

grant truncate on table "public"."plan" to "service_role";

grant update on table "public"."plan" to "service_role";


