name: Publish to VS Code Marketplace

on:
  push:
    paths:
      - "packages/vscode/**"

jobs:
  publish:
    runs-on: ubuntu-latest

    env:
      SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
      VSCE_PAT: ${{ secrets.VSCE_PAT }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"
          cache-dependency-path: |
            packages/vscode/package-lock.json
            packages/vscode/node_modules
            package-lock.json
            node_modules

      - name: Install dependencies
        run: npm ci

      - name: Publish extension
        run: npm run publish
        working-directory: packages/vscode

      - uses: EndBug/add-and-commit@v9
        with:
          message: Bumps the package.json version
          default_author: github_actions
